### ISSUE TITLE
Creating Promise Error / Can not convert to Object

### ISSUE THREAD

**Issue by mirkofisic** [zouyaoji/vue-cesium-demo#14]
I want to load cesium with vuejs, in this project i use VUE3 and quasar framework, when i try to load cesium-viewer without vc-config-provider component i got this error:
```
useViewer.ts:455 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__scriptPromise')
    at beforeLoad (useViewer.ts:455:61)
    at load (useViewer.ts:464:11)
    at useViewer.ts:1083:7
```

when i try to load cesium-viewer with vc-config-provider component i got this error:
```
vue-router.mjs:3428 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keysOf (objects.ts:2:39)
    at mergeConfig (index.ts:39:48)
    at ReactiveEffect.fn (index.ts:29:12)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at get value [as value] (reactivity.esm-bundler.js:1144:39)
    at provideGlobalConfig (index.ts:33:34)
    at setup (index.ts:21:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
triggerError @ vue-router.mjs:3428
(anonymous) @ vue-router.mjs:3464
Promise.catch (async)
handleScroll @ vue-router.mjs:3464
finalizeNavigation @ vue-router.mjs:3312
(anonymous) @ vue-router.mjs:3184
Promise.then (async)
pushWithRedirect @ vue-router.mjs:3153
push @ vue-router.mjs:3080
navigateToRouterLink @ use-router-link.js?v=22f2048f:250
onClick @ QItem.js?v=22f2048f:104
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
objects.ts:2 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keysOf (objects.ts:2:39)
    at mergeConfig (index.ts:39:48)
    at ReactiveEffect.fn (index.ts:29:12)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at get value [as value] (reactivity.esm-bundler.js:1144:39)
    at provideGlobalConfig (index.ts:33:34)
    at setup (index.ts:21:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)

```
code:
```
<template>
  <q-page class="flex" style="overflow: hidden; max-height:  calc(100vh - 55px); height: calc(100vh - 55px);">
    <q-no-ssr>
	  <vc-config-provider :cesium-path="vcConfig.cesiumPath">
        <vc-viewer ref="viewerRef" @ready="onViewerReady"> </vc-viewer>
      </vc-config-provider>
    </q-no-ssr>
  </q-page>
</template>

<script setup>
import { VcConfigProvider, VcViewer } from 'vue-cesium'
import { VcReadyObject } from 'vue-cesium/es/utils/types'
import { ref, reactive} from 'vue'
import { onMounted, } from 'vue'
import 'vue-cesium/dist/index.css'

const viewerRef = ref(null)
const onViewerReady = (readyObj) => {
  console.log(readyObj.Cesium) // Cesium namespace object
  console.log(readyObj.viewer) // instanceof Cesium.Viewer
}

const vcConfig = reactive({
    cesiumPath: 'https://unpkg.com/cesium@latest/Build/Cesium/Cesium.js',
    accessToken: 'xxxxxxxx'
})

onMounted(() => {
  console.log('onMounted')
  viewerRef.value.creatingPromise.then((readyObj) => {
    console.log(readyObj.Cesium) // Cesium namespace object
    console.log(readyObj.viewer) // instanceof Cesium.Viewer
  })
})
</script>
```

**Comment by zouyaoji** [comment]
May want to upgrade to vue-cesium to the latest version. There is no problem with my local test, but there are a lot of unfinished contents, and there is no way to submit the code for the time being.

**Comment by zouyaoji** [comment]
@mirkofisic The project has been updated, you can pull the latest code and try again

**Comment by mirkofisic** [comment]
@zouyaoji Now I realize that I reported the problem in the wrong place, this is a demo repository, I'm implementing this in my existing project, or if you can tell me briefly which part of the code I need to change? Or is it enough to update the vue-cesium package? how ever thank you very much!

**Comment by zouyaoji** [comment]
I have not reproduced the problem with the code you posted, please provide a reproduced use case so that I can figure out why.

**Comment by mirkofisic** [comment]
Here is the complete code:
https://github.com/mirkofisic/cesiumtest

**Comment by zouyaoji** [comment]
Thanks for the feedback. It seems that there is a problem with importing VcViewer and VcConfigProvider on demand, which will be fixed in the next version.

For now, please import vue-cesium in full.
![image](https://user-images.githubusercontent.com/24430116/188250952-111f9fab-5d0a-4577-b3d7-d18640f53e15.png)
![image](https://user-images.githubusercontent.com/24430116/188250960-6ab6b3a4-2b26-43fa-b028-03dce70a9660.png)

**Comment by mirkofisic** [comment]
@zouyaoji Thank you very much works very well :) cheers
I know this is off topic, map is loaded correctly but when I zoom globe, the image of the map is not adapted to zoom, how to adjust it, or perhaps an even better question, how to use images of the country, for example, from maptiler? is it possible?

**Comment by zouyaoji** [comment]
https://zouyaoji.top/vue-cesium/#/en-US/component/quickstart#how-to-get-viewer-instance-in-other-vue-components

https://zouyaoji.top/vue-cesium/#/en-US/component/providers/vc-imagery-provider-tms

**Comment by zouyaoji** [comment]
fixed in v3.0.19.

**Comment by mirkofisic** [comment]
Thank you veru much, cheers

**Comment by zouyaoji** [comment]
A piece of cake, welcome to give vue-cesium a star to encourage it.
